### ISSUE TITLE
Register Does Not Seem To Want To Work

### ISSUE THREAD

**Issue by jhughes94** [ChristopherDay/Gangster-Legends-V2#16]
When I click on Register, it gives me a HTTP 500 error, is anyone able to assist?

**Comment by ChristopherDay** [comment]
fixed in 2.2.0

**Comment by jhughes94** [comment]
This is actually still an issue for me, can you please assist?
